name: Publicar Cálculo Numérico

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: raphateixeira/.github/.github/workflows/quarto-publish.yml@main
    with:
      needs_python: true
      python_packages: "numpy scipy matplotlib"
      needs_r: true
      r_packages: "knitr, rmarkdown, reticulate, tikzDevice, magick, pdftools"
      needs_magick_system_deps: true
      needs_tinytex: true
      tinytex_packages: "pgf standalone"
